reverting sphinx to >= 1.4"
Was getting error, see https://readthedocs.org/projects/jupman/builds/6305228/

 python /home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/bin/sphinx-build -T -b epub -d _build/doctrees-epub -D language=en . _build/epub
Running Sphinx v1.6.5
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
building [mo]: targets for 0 po files that are out of date
building [epub]: targets for 6 source files that are out of date
updating environment: 6 added, 0 changed, 0 removed
reading sources... [ 16%] README
reading sources... [ 33%] index
reading sources... [ 50%] intro
reading sources... [ 66%] jupman-tests
reading sources... [ 83%] past-exams/README
reading sources... [100%] usage

/home/docs/checkouts/readthedocs.org/user_builds/jupman/checkouts/latest/index.rst:24: WARNING: toctree glob pattern 'past-exams/**/exam-*' didn't match any documents
/home/docs/checkouts/readthedocs.org/user_builds/jupman/checkouts/latest/jupman-tests.ipynb.rst: WARNING: file not found: '_static/trial.odt'
/home/docs/checkouts/readthedocs.org/user_builds/jupman/checkouts/latest/jupman-tests.ipynb.rst: WARNING: file not found: '_static/trial.pdf'
/home/docs/checkouts/readthedocs.org/user_builds/jupman/checkouts/latest/usage.ipynb.rst: WARNING: file not found: 'jupman.readthedocs.io'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/jupman/checkouts/latest/README.md: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/jupman/checkouts/latest/past-exams/README.md: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [ 16%] README
writing output... [ 33%] index
writing output... [ 50%] intro
writing output... [ 66%] jupman-tests

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 397, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 434, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 443, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/sphinx/builders/_epub_base.py", line 359, in write_doc
    StandaloneHTMLBuilder.write_doc(self, docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/sphinx/builders/html.py", line 555, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/sphinx/writers/html.py", line 56, in translate
    self.document.walkabout(visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/nbsphinx.py", line 1304, in visit_admonition_html
    self.set_first_last(node)
AttributeError: 'HTML5Translator' object has no attribute 'set_first_last'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupman/envs/latest/lib/python3.5/site-packages/nbsphinx.py", line 1304, in visit_admonition_html
    self.set_first_last(node)
AttributeError: 'HTML5Translator' object has no attribute 'set_first_last'
The full traceback has been saved in /tmp/sphinx-err-bah2hq_d.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!