updated to jupman 3.1
- many fixes
- had to convert changelog.md to changelog.ipynb because apparently system was not able to
  resolve correct links to existing .ipynb files
  In particular, nbsphinx stopped execution with error:

     NotImplementedError: Unknown node: pending_xref